### PR TITLE
Cleaning up of event listeners upon unmount

### PR DESCRIPTION
**Pull request by jln-dk**

### CODE REVIEW

**Comment by jln-dk** [comment]
@aksonov what do you think?

**Comment by jln-dk** [comment]
Thanks for merging @aksonov . Are you going to make a new release on npm?

**Comment by aksonov** [comment]
done

**Comment by jln-dk** [comment]
thanks!

**Comment by jln-dk** [comment]
Maybe I was too quick.. Let me provide a fix.

**Pull request merged**
