### PR TITLE
Add SASLMechanism support

### PR DESCRIPTION
**Pull request by HugoMaster**
Simply black listing SASLMechanisms and leave one that is want to be used.

### CODE REVIEW

**Comment by Froelund** [comment]
Great @HugoMaster. Did you test the XmppDemo to see if it still works?

**Comment by Froelund** [comment]
@HugoMaster ?

**Comment by HugoMaster** [comment]
Sorry was out for one week, will test it today.

**Comment by HugoMaster** [comment]
No could not connect to this server, with any SASLMechanism, unfortunately this not work for this server. Tried with different SASL Mechanisms but no luck. Can close this PR.

**Comment by aksonov** [comment]
@HugoMaster Strange, iOS SASL works fine with demo...

**Comment by HugoMaster** [comment]
iOS yeah, its working, for android its either NoSaslMechanisms known, or for example specific sasl mechanism not working. 

I have testing it on my priv server and its working.

**Pull request closed without merging**
